package:
  name: q
  version: 3.2.1

source:
  fn: windows.zip # [win]
  url: http://kx.com/347_d0szre-fr8917_llrsT4Yle-5839sdX/3.2/windows.zip # [win]
  fn: macosx.zip # [osx]
  url: http://kx.com/347_d0szre-fr8917_llrsT4Yle-5839sdX/3.2/macosx.zip # [osx]
  fn: linux.zip # [linux]
  url: http://kx.com/347_d0szre-fr8917_llrsT4Yle-5839sdX/3.2/linux.zip # [linux]

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

about:
  home: http://code.kx.com
  license: Freeware
