package: kdbpy
user: cpcloud

platform:
 - win-64
 - osx-64

engine:
 - python=2.7

install:
  - conda config --add channels blaze
  - conda config --add channels cpcloud

before_script:
  - python -V

script:
  - conda build recipes/kdbpy --python=2.7

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
