package: kdbpy
user: cpcloud

platform:
 - win-64
 - osx-64

engine:
 - python=2.7

install:
  - conda config --force --add channels blaze --add channels cpcloud
  - conda install pytest

before_script:
  - python -V

script:
  - conda build recipes/kdbpy --python=2.7 --no-test
  - conda install kdbpy --use-local
  - py.test -x --doctest-modules --pyargs kdbpy

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
