package: kdbpy
user: cpcloud

platform:
 - osx-64

engine:
 - python=2.7

install:
  - conda config --add channels blaze --add channels cpcloud
  - pip install 'git+git://github.com/ContinuumIO/datashape.git'

before_script:
  - python -V

script:
  - conda build conda.recipe

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
