package: kdbpy
user: cpcloud

platform:
 - win-64
 - linux-32
 - linux-64
 - osx-64

engine:
 - python=2.7

install:
  - conda config --force --add channels blaze --add channels cpcloud

before_script:
  - python -V

script:
  - conda build conda.recipe

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
