language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - pip install .
    - pip install -r recommended-requirements.txt
    - pip install coverage --use-mirrors

script:
    - py.test --doctest-modules into

after_success:
    - pip install coveralls --use-mirrors ; coveralls

notifications:
  email: false
