package:
  name: kdbpy
  version: 0.0.4

build:
    number: 1

requirements:
  build:
    - python
    - numpy
    - pandas

  run:
    - python
    - numpy
    - pandas
    - blaze
    - q
    - qpython
    - pytest

#test:
#  requires:
#    - pytest

#  commands:
#    - py.test -r sxX --verbose --pyargs kdbpy

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
