package:
  name: kdbpy
  version: 0.0.9

build:
    number: 1

requirements:
  build:
    - python

  run:
    - python
    - blaze
    - q
    - qpython
    - ipython
    - ipython-notebook
    - psutil

test:
  requires:
    - pytest

  commands:
    - py.test -vx -r sxX --doctest-modules --pyargs kdbpy

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
