package:
  name: kdbpy
  version: 0.0.9

build:
    number: 1

requirements:
  build:
    - python
    - blaze
    - q
    - qpython
    - ipython
    - ipython-notebook
    - psutil

  run:
    - python
    - blaze
    - q
    - qpython
    - ipython
    - ipython-notebook
    - psutil

test:
  requires:
    - pytest

  commands:
    - python -c "import kdbpy; kdbpy.test()"

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
