package:
  name: kdbpy
  version: 0.0.8

build:
    number: 1

requirements:
  build:
    - python

  run:
    - python
    - blaze
    - q
    - qpython
    - ipython
    - ipython-notebook
    - psutil

test:
  requires:
    - pytest
    # - runipy

  commands:
    - py.test -s -r sxX --doctest-modules --pyargs kdbpy

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
