package:
  name: kdbpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../

requirements:
  build:
    - python
    - blaze
    - q
    - qpython
    - ipython

  run:
    - python
    - blaze
    - q
    - qpython
    - ipython

test:
  requires:
    - pytest

  imports:
    - kdbpy
    - qpython
    - blaze

  commands:
    - py.test -sx -v $SRC_DIR/kdbpy/tests/test_kdb.py::test_basic $SRC_DIR/kdbpy/tests/test_kdb.py::test_basic_inuse

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
