package:
  name: kdbpy
  version: 0.0.9

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python ==2.7.8
    - blaze
    - q >=3.2.1
    - qpython
    - ipython
    - ipython-notebook
    - psutil

  run:
    - python ==2.7.8
    - blaze
    - q >=3.2.1
    - qpython
    - ipython
    - ipython-notebook
    - psutil

test:
  requires:
    - pytest

  imports:
    - kdbpy

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
