package:
  name: kdbpy
  version: 0.1.4

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python
    - blaze
    - q
    - qpython
    - ipython

  run:
    - python
    - blaze
    - q
    - qpython
    - ipython

test:
  requires:
    - pytest

  imports:
    - kdbpy

  commands:
    - py.test -sx --pyargs kdbpy --doctest-modules

about:
  home: https://github.com/ContinuumIO/kdbpy
  license: BSD
